# Utiliser une image Node.js officielle
FROM node:18-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Installer les dépendances système nécessaires (ps, prgrep, etc.)
RUN apt-get update \
  && apt-get install -y --no-install-recommends procps \
  && rm -rf /var/lib/apt/lists/*

# Copier les fichiers package.json et package-lock.json dans le conteneur
COPY package*.json ./

# Installer les dépendances (inclut les devDependencies en mode dev)
RUN npm install

# Installer le CLI de NestJS globalement
RUN npm install -g @nestjs/cli

# Copier le reste de l'application
COPY . .

# Exposer le port utilisé par NestJS
EXPOSE 5000

# Commande à exécuter au démarrage pour exécuter les migrations et démarrer en mode dev
# CMD ["sh", "-c", "npm run start:migrate && npm run start:dev"]
CMD ["sh", "-c", "npm run start:dev"]