import { GetTeacherInvoicesNumberForCurrentMonthQueryResult } from './getTeacherInvoicesNumberForCurrentMonth.queryResult';

export interface GetTeacherInvoicesNumberForCurrentMonthTeacherInvoiceRepository {
  getTeacherInvoicesNumberForCurrentMonth(): Promise<GetTeacherInvoicesNumberForCurrentMonthQueryResult>;
}