import { GetTeacherInvoicesNumberForCurrentMonthQueryResult } from './getTeacherInvoicesNumberForCurrentMonth.queryResult';

export interface GetTeacherInvoicesNumberForCurrentMonthTeacherInvoiceRepository {
  getTeacherInvoicesNumberForCurrentMonth(teacherId: number): Promise<GetTeacherInvoicesNumberForCurrentMonthQueryResult>;
}