import { GetTeacherInvoicesNumberForCurrentMonthQueryResult } from './getTeacherInvoicesNumberForCurrentMonth.queryResult';

export interface GetTeacherInvoicesNumberForCurrentMonthTeacherInvoiceRepository {
  getTeacherInvoicesNumberForCurrentMonth(teacherId: string): Promise<GetTeacherInvoicesNumberForCurrentMonthQueryResult>;
}