#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"

BRANCH_NAME=$(git symbolic-ref --short HEAD)

if [ "$BRANCH_NAME" = "feature/teacher-invoice" ]; then
  echo "🧪  Launching frontend tests for $BRANCH_NAME ..."
  cd frontend || exit 1
  npm run test:ci || exit 1
  cd ..

  echo "🧪  Launching backend tests for $BRANCH_NAME ..."
  cd backend || exit 1
  npm run test:unit || exit 1
  npm run test:e2e || exit 1
  cd ..
else
  echo "➡️  Skipping tests (branch $BRANCH_NAME)"
fi
